### ISSUE TITLE
'str" object has no attribute 'decode' using sct_deepseg_sc 

### ISSUE THREAD

**Issue by sandrinebedard** [neuropoly/spinalcordtoolbox#3019]
### Description

When running _sct_deepseg_sc -i anat/sub-1000032_T2w.nii.gz -c t2_

This error appears:
![image](https://user-images.githubusercontent.com/71230552/98472212-94920600-21bf-11eb-9aa7-0857bd75b8f4.png)

The same thing happens when using t1w image. This was not an issue when using SCT 4.3. Now using SCT master's version.
### Steps to Reproduce

0. Install SCT git-master-c6e489e764ff54244bb5c6abc3a010c6412d520e*

1. Go into duke/mri/uk_biobank/1000032

2. Unzip the file, change to BIDS

3.  Run sct_deepseg_sc -i anat/sub-1000032_T2w.nii.gz -c t2

**Expected behavior:** I was able to succesfully segment this same image before.

**Actual behavior:** (see screenshot above)

**Comment by joshuacwnewton** [comment]
Hi @sandrinebedard. Thank you for reporting this issue. I believe this issue was caused by #2987 and has been fixed recently by #2988. 

Could you please try installing the newest version of SCT, [`v5.0.0`](https://github.com/neuropoly/spinalcordtoolbox/releases/tag/5.0.0)? :slightly_smiling_face:

**Comment by sandrinebedard** [comment]
Hi @joshuacwnewton, thanks for the info! I installed the newest version of SCT v5.0.0, and it worked, thanks again :)
